ticket:1673 - RasdaPy_add the error message for error query as same as output from rasql
Summary: The error message is missing from error query in RasdaPy and it is hard to understand problem. Therefore, RasdaPy should return error message as same as from rasql to understand error in query easier.

Test Plan:
Tested with error query, it will throw exception with a detail error, e.g:

Exception: Error executing query 'select c1 from test_mr as c', error message 'rasdaman error 357: Execution error 357 in line 1, column 8, near token c1: Variable is unknown.'

Reviewers: vmerticariu, dmisev

Differential Revision: http://codereview.rasdaman.org/D528